module;
#include <wobjectimpl.h>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTextEdit>
#include <QLineEdit>
#include <QPushButton>
#include <QLabel>
#include <QTimer>
module Artifact.Widgets.ExpressionCopilotWidget;

namespace Artifact {
    W_OBJECT_IMPL(ArtifactExpressionCopilotWidget)

    class ArtifactExpressionCopilotWidget::Impl {
    public:
        QLineEdit* promptInput;
        QTextEdit* codeOutput;
        QPushButton* generateBtn;
        QPushButton* applyBtn;

        void setupUi(QWidget* parent) {
            auto layout = new QVBoxLayout(parent);
            layout->setContentsMargins(8, 8, 8, 8);
            layout->setSpacing(6);

            auto headerLayout = new QHBoxLayout();
            auto iconLabel = new QLabel(QString::fromUtf8("✨"));
            auto titleLabel = new QLabel("Expression Copilot");
            titleLabel->setStyleSheet("font-weight: bold; font-size: 14px;");
            headerLayout->addWidget(iconLabel);
            headerLayout->addWidget(titleLabel);
            headerLayout->addStretch();
            layout->addLayout(headerLayout);

            promptInput = new QLineEdit();
            promptInput->setPlaceholderText("Describe the motion you want... (e.g. wiggle 3 times a second)");
            layout->addWidget(promptInput);

            codeOutput = new QTextEdit();
            codeOutput->setPlaceholderText("// Generated expression will appear here...");
            codeOutput->setMaximumHeight(150);
            layout->addWidget(codeOutput);

            auto btnLayout = new QHBoxLayout();
            generateBtn = new QPushButton("Generate");
            applyBtn = new QPushButton("Apply");
            btnLayout->addStretch();
            btnLayout->addWidget(generateBtn);
            btnLayout->addWidget(applyBtn);
            layout->addLayout(btnLayout);
        }
    };

    ArtifactExpressionCopilotWidget::ArtifactExpressionCopilotWidget(QWidget* parent)
        : QWidget(parent), impl_(new Impl()) {
        impl_->setupUi(this);

        connect(impl_->generateBtn, &QPushButton::clicked, this, [this]() {
            QString prompt = impl_->promptInput->text();
            if (prompt.isEmpty()) return;

            impl_->codeOutput->setText("// Generating...");
            
            QTimer::singleShot(600, this, [this, prompt]() {
                QString result = "// Auto-generated by Artifact AI\n";
                if (prompt.contains("wiggle", Qt::CaseInsensitive) || prompt.contains(QString::fromUtf8("揺"), Qt::CaseInsensitive)) {
                    result += "wiggle(3, 50);\n";
                } else if (prompt.contains("loop", Qt::CaseInsensitive) || prompt.contains(QString::fromUtf8("ループ"), Qt::CaseInsensitive)) {
                    result += "loopOut(\"cycle\");\n";
                } else {
                    result += "value + [10, 0]; // Default placeholder\n";
                }
                impl_->codeOutput->setText(result);
            });
        });
    }

    ArtifactExpressionCopilotWidget::~ArtifactExpressionCopilotWidget() {
        delete impl_;
    }

    QSize ArtifactExpressionCopilotWidget::sizeHint() const {
        return { 300, 250 };
    }
}
