module;

#include <algorithm>

module Artifact.Widgets.InspectorEffectCatalog;

import Artifact.Effect.Abstract;

namespace Artifact {

QString stageDisplayName(EffectPipelineStage stage) {
  switch (stage) {
  case EffectPipelineStage::Generator:
    return QStringLiteral("Generator");
  case EffectPipelineStage::GeometryTransform:
    return QStringLiteral("Geo Transform");
  case EffectPipelineStage::MaterialRender:
    return QStringLiteral("Material");
  case EffectPipelineStage::Rasterizer:
    return QStringLiteral("Rasterizer");
  case EffectPipelineStage::LayerTransform:
    return QStringLiteral("Layer Transform");
  }
  return QStringLiteral("Effects");
}

std::vector<EffectCatalogEntry> buildEffectCatalogEntries() {
  return {
      {EffectPipelineStage::Generator, QStringLiteral("fractal_noise"),
       QStringLiteral("Fractal Noise"), QStringLiteral("Generator"),
       QStringLiteral("Procedural texture and noise source."), QStringLiteral("noise texture procedural")},
      {EffectPipelineStage::Generator,
       QStringLiteral("procedural_texture"),
       QStringLiteral("Procedural Texture"), QStringLiteral("Generator"),
       QStringLiteral("Pattern-based texture generator."),
       QStringLiteral("texture procedural pattern")},
      {EffectPipelineStage::GeometryTransform, QStringLiteral("twist"),
       QStringLiteral("Twist"), QStringLiteral("Geometry"),
       QStringLiteral("Twist geometry around an axis."),
       QStringLiteral("deform rotate geometry")},
      {EffectPipelineStage::GeometryTransform, QStringLiteral("bend"),
       QStringLiteral("Bend"), QStringLiteral("Geometry"),
       QStringLiteral("Bend geometry across a domain."),
       QStringLiteral("deform curve geometry")},
      {EffectPipelineStage::MaterialRender, QStringLiteral("pbr_material"),
       QStringLiteral("PBR Material"), QStringLiteral("Material"),
       QStringLiteral("Assign physically-based material controls."),
       QStringLiteral("material metal roughness shader")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("blur"),
       QStringLiteral("Blur"), QStringLiteral("Blur"),
       QStringLiteral("Simple raster blur."), QStringLiteral("soften blur")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("frame_blend"),
       QStringLiteral("Frame Blend"), QStringLiteral("Blur"),
       QStringLiteral("Blend neighboring frames for temporal motion blur."),
       QStringLiteral("frame blend temporal ghost motion blur")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("time_blur"),
       QStringLiteral("Time Blur"), QStringLiteral("Blur"),
       QStringLiteral("Blur across time using sampled neighboring frames."),
       QStringLiteral("time blur temporal motion")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("vector_blur"),
       QStringLiteral("Vector Blur"), QStringLiteral("Blur"),
       QStringLiteral("Apply blur using per-pixel velocity vectors."),
       QStringLiteral("vector blur velocity motion")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.blur.gaussian"),
       QStringLiteral("Gaussian Blur"), QStringLiteral("Blur"),
       QStringLiteral("Classic gaussian image blur."),
       QStringLiteral("soft blur gaussian")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("anisotropic_flow_blur"),
       QStringLiteral("Anisotropic Flow Blur"), QStringLiteral("Blur"),
       QStringLiteral("Edge-preserving blur that follows local image flow."),
       QStringLiteral("flow directional edge anisotropic blur")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("reaction_diffusion_blur"),
       QStringLiteral("Reaction Diffusion Blur"), QStringLiteral("Blur"),
       QStringLiteral("Organic blur with self-organizing cellular patterns."),
       QStringLiteral("reaction diffusion organic cellular blur melt")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("aperture_shape_blur"),
       QStringLiteral("Aperture Shape Blur"), QStringLiteral("Blur"),
       QStringLiteral("FFT lens blur using built-in or custom PSF shapes."),
       QStringLiteral("aperture bokeh lens psf fft heart polygon blur")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("glow"),
       QStringLiteral("Glow"), QStringLiteral("Glow"),
       QStringLiteral("Bloom around bright areas."),
       QStringLiteral("bloom light glow")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("drop_shadow"),
       QStringLiteral("Drop Shadow"), QStringLiteral("Light"),
       QStringLiteral("Shadow cast behind the layer."),
       QStringLiteral("shadow depth offset")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("directional_glow"),
       QStringLiteral("Directional Glow / Streaks"),
       QStringLiteral("Glow"),
       QStringLiteral("Stretch glow into directional streaks."),
       QStringLiteral("streaks anamorphic directional glow")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("edge_bloom"),
       QStringLiteral("Edge Bloom"), QStringLiteral("Glow"),
       QStringLiteral("Bloom driven by edge contrast."),
       QStringLiteral("edges bloom")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("chromatic_glow"),
       QStringLiteral("Chromatic Glow"), QStringLiteral("Glow"),
       QStringLiteral("Color-split glow bloom."),
       QStringLiteral("rgb chromatic aberration glow")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("reactive_glow"),
       QStringLiteral("Reactive Glow"), QStringLiteral("Glow"),
       QStringLiteral("Animated glow response with temporal flavor."),
       QStringLiteral("reactive animated glow")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("liquid_glow"),
       QStringLiteral("Liquid Glow"), QStringLiteral("Glow"),
       QStringLiteral("Fluid-style glow diffusion."),
       QStringLiteral("liquid glow fluid")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("residual_glow"),
       QStringLiteral("Residual Glow"), QStringLiteral("Glow"),
       QStringLiteral("Afterimage-like lingering bloom."),
       QStringLiteral("residual afterimage glow")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("physical_halation"),
       QStringLiteral("Physical Halation"), QStringLiteral("Film"),
       QStringLiteral("Red-shifted highlight scattering inspired by film emulsion."),
       QStringLiteral("film halation red bloom highlight")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("luminescence_caustics"),
       QStringLiteral("Luminescence Caustics"), QStringLiteral("Glow"),
       QStringLiteral("Animated light-ridge patterns driven by highlights and edges."),
       QStringLiteral("caustics light crystal water magic glow")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("simple_rain"),
       QStringLiteral("Simple Rain"), QStringLiteral("Generate"),
       QStringLiteral("Screen-space rain streaks with wind, depth, and splashes."),
       QStringLiteral("rain weather streak wind splash generate")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("vector_flow_glitch"),
       QStringLiteral("Vector Flow Glitch"), QStringLiteral("Stylize"),
       QStringLiteral("Tear pixels along local contours with chromatic splitting."),
       QStringLiteral("glitch vector flow edge tear chromatic")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("builtin.glitch"), QStringLiteral("Glitch"),
       QStringLiteral("Stylize"),
       QStringLiteral("Displace image blocks with animated digital glitch artifacts."),
       QStringLiteral("glitch digital displacement tear rgb stylize")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("halftone"),
       QStringLiteral("Halftone"), QStringLiteral("Stylize"),
       QStringLiteral("Convert luminance into a configurable halftone pattern."),
       QStringLiteral("halftone dots print comic stylize")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("builtin.old_tv"),
       QStringLiteral("Old TV"), QStringLiteral("Film"),
       QStringLiteral("Add scanlines, noise, and analog television distortion."),
       QStringLiteral("old tv crt scanline analog vintage noise")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("sharpen"),
       QStringLiteral("Sharpen"), QStringLiteral("Detail"),
       QStringLiteral("Enhance local contrast around image edges."),
       QStringLiteral("sharpen detail edge contrast")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("find_edges"),
       QStringLiteral("Find Edges"), QStringLiteral("Detail"),
       QStringLiteral("Extract luminance boundaries from the image."),
       QStringLiteral("find edges outline sobel contour detail")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("add_noise"),
       QStringLiteral("Add Noise"), QStringLiteral("Film"),
       QStringLiteral("Add controlled image noise for texture or film grain."),
       QStringLiteral("noise grain film texture random")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("radial_shadow"),
       QStringLiteral("Radial Shadow"), QStringLiteral("Light"),
       QStringLiteral("Cast a soft shadow from a radial light direction."),
       QStringLiteral("radial shadow light vignette depth")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("chromatic_relief"),
       QStringLiteral("Chromatic Relief"), QStringLiteral("Stylize"),
       QStringLiteral("Embossed luminance relief with directional RGB separation."),
       QStringLiteral("chromatic relief emboss edge rgb split stylize")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("film_damage"),
       QStringLiteral("Film Damage"), QStringLiteral("Film"),
       QStringLiteral("Grain, dust, scratches, gate weave, flicker, and film burn."),
       QStringLiteral("film damage grain dust scratch burn flicker vintage")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("vignette"),
       QStringLiteral("Vignette"), QStringLiteral("Light"),
       QStringLiteral("Darken the frame edges with a soft radial falloff."),
       QStringLiteral("vignette edges darken falloff lens")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("stripes"),
       QStringLiteral("Stripes"), QStringLiteral("Generate"),
       QStringLiteral("Repeating stripe pattern generator."),
       QStringLiteral("stripes lines pattern generate")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("voronoi"),
       QStringLiteral("Voronoi"), QStringLiteral("Generate"),
       QStringLiteral("Cell-based voronoi pattern generator."),
       QStringLiteral("voronoi cells pattern generate procedural")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("bricks"),
       QStringLiteral("Bricks"), QStringLiteral("Generate"),
       QStringLiteral("Brick wall pattern with mortar and offset rows."),
       QStringLiteral("bricks wall mortar pattern generate")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("hex_grid"),
       QStringLiteral("Hex Grid"), QStringLiteral("Generate"),
       QStringLiteral("Hexagonal grid pattern generator."),
       QStringLiteral("hex grid hexagon honeycomb pattern generate")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("edge"),
       QStringLiteral("Edge"), QStringLiteral("Detail"),
       QStringLiteral("Edge-detected outline pass for stylized contours."),
       QStringLiteral("edge outline contour detect detail")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("effect.colorcorrection.invert"),
       QStringLiteral("Invert"), QStringLiteral("Color"),
       QStringLiteral("Invert individual color channels or the whole image."),
       QStringLiteral("invert negative channel color")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.brightness"),
       QStringLiteral("Brightness / Contrast"),
       QStringLiteral("Color"), QStringLiteral("Basic tonal correction."),
       QStringLiteral("brightness contrast tone")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.exposure"),
       QStringLiteral("Exposure"), QStringLiteral("Color"),
       QStringLiteral("Exposure and intensity correction."),
       QStringLiteral("exposure tone")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.tint"),
       QStringLiteral("Tint"), QStringLiteral("Color"),
       QStringLiteral("Shift temperature and tint."),
       QStringLiteral("tint white balance temperature")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.photofilter"),
       QStringLiteral("Photo Filter"), QStringLiteral("Color"),
       QStringLiteral("Camera-style photo filter wash."),
       QStringLiteral("photo filter color")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.gradientramp"),
       QStringLiteral("Gradient Ramp"), QStringLiteral("Color"),
       QStringLiteral("Map tones through a gradient."),
       QStringLiteral("gradient ramp remap")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.fill"),
       QStringLiteral("Fill"), QStringLiteral("Color"),
       QStringLiteral("Solid recolor fill."),
       QStringLiteral("fill solid recolor")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.hsl"),
       QStringLiteral("Hue / Saturation"), QStringLiteral("Color"),
       QStringLiteral("Hue and saturation correction."),
       QStringLiteral("hue saturation color")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.colorwheels"),
       QStringLiteral("Color Wheels"), QStringLiteral("Color"),
       QStringLiteral("Lift/gamma/gain style wheel controls."),
       QStringLiteral("color wheels grade")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.curves"),
       QStringLiteral("Curves"), QStringLiteral("Color"),
       QStringLiteral("Curve-based tonal shaping."),
       QStringLiteral("curves rgb luma")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("builtin.posterize"),
       QStringLiteral("Posterize"), QStringLiteral("Stylize"),
       QStringLiteral("Reduce color levels through the Curves posterize preset."),
       QStringLiteral("posterize quantize levels color stylize")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("builtin.pixelate"),
       QStringLiteral("Pixelate"), QStringLiteral("Stylize"),
       QStringLiteral("Reduce image detail into configurable mosaic cells."),
       QStringLiteral("pixelate mosaic blocks stylize")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("mosaic"),
       QStringLiteral("Mosaic"), QStringLiteral("Stylize"),
       QStringLiteral("Apply configurable mosaic cells to the image."),
       QStringLiteral("mosaic pixel blocks stylize")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("mirror"), QStringLiteral("Mirror"), QStringLiteral("Stylize"),
       QStringLiteral("Mirror the image around a configurable axis."),
       QStringLiteral("mirror reflection axis flip stylize")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.tritone"),
       QStringLiteral("Tritone"), QStringLiteral("Color"),
       QStringLiteral("Three-color remap treatment."),
       QStringLiteral("tritone duotone color")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.colorama"),
       QStringLiteral("Colorama"), QStringLiteral("Color"),
       QStringLiteral("Stylized palette remapping."),
       QStringLiteral("palette psychedelic colorama")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.colorbalance"),
       QStringLiteral("Color Balance"), QStringLiteral("Color"),
       QStringLiteral("Balance color channels."),
       QStringLiteral("balance channel color")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.levels"),
       QStringLiteral("Levels"), QStringLiteral("Color"),
       QStringLiteral("Input/output black and white levels."),
       QStringLiteral("levels histogram")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.channelmixer"),
       QStringLiteral("Channel Mixer"), QStringLiteral("Color"),
       QStringLiteral("Mix and rebalance channels."),
       QStringLiteral("channel mixer rgb")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.selectivecolor"),
       QStringLiteral("Selective Color"), QStringLiteral("Color"),
       QStringLiteral("Selective hue-based correction."),
       QStringLiteral("selective color cmyk")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("lift_gamma_gain"),
       QStringLiteral("Lift / Gamma / Gain"), QStringLiteral("Color"),
       QStringLiteral("Three-way color grading controls."),
       QStringLiteral("lift gamma gain grade")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("lens_distortion"),
       QStringLiteral("Lens Distortion"), QStringLiteral("Distort"),
       QStringLiteral("Warp image using lens characteristics."),
       QStringLiteral("distortion lens optics")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("optics_compensation"),
       QStringLiteral("Optics Compensation"), QStringLiteral("Distort"),
       QStringLiteral("Compensate or exaggerate wide-angle lens distortion."),
       QStringLiteral("optics compensation lens distortion fisheye")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("displacement_map"),
       QStringLiteral("Displacement Map"), QStringLiteral("Distort"),
       QStringLiteral("Warp using displacement textures."),
       QStringLiteral("displacement map distort")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("image_morph"),
       QStringLiteral("Image Morph"), QStringLiteral("Distort"),
       QStringLiteral("Morph toward a target image using corresponding control points."),
       QStringLiteral("image morph warp control points blend")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("turbulent_displace"),
       QStringLiteral("Turbulent Displace"), QStringLiteral("Distort"),
       QStringLiteral("Procedural turbulent displacement with controllable detail."),
       QStringLiteral("turbulent displace noise warp procedural")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("screen_shake"),
       QStringLiteral("Screen Shake"), QStringLiteral("Transform"),
       QStringLiteral("Animated 2D screen shake / offset."),
       QStringLiteral("shake camera offset jitter")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("time_displacement"),
       QStringLiteral("Time Displacement"), QStringLiteral("Time"),
       QStringLiteral("Offset sampling in time."),
       QStringLiteral("time temporal displacement")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("chroma_key"),
       QStringLiteral("Chroma Key"), QStringLiteral("Keying"),
       QStringLiteral("Key out a color range."),
       QStringLiteral("green screen keying")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("luma_key"),
       QStringLiteral("Luma Key"), QStringLiteral("Keying"),
       QStringLiteral("Key out pixels by luminance range."),
       QStringLiteral("luma key luminance matte brightness")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("difference_key"),
       QStringLiteral("Difference Key"), QStringLiteral("Keying"),
       QStringLiteral("Key out pixels close to a reference color."),
       QStringLiteral("difference key reference color matte")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("ibk_keyer"),
       QStringLiteral("IBK Keyer"), QStringLiteral("Keying"),
       QStringLiteral("Difference-based keyer with clean-plate support."),
       QStringLiteral("ibk keyer clean plate screen matte")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("difference_matte"),
       QStringLiteral("Difference Matte"), QStringLiteral("Keying"),
       QStringLiteral("Generate a matte from a reference image."),
       QStringLiteral("difference matte reference image keying")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("wave"),
       QStringLiteral("Wave"), QStringLiteral("Distort"),
       QStringLiteral("Wave deformation effect."),
       QStringLiteral("wave distort ripple")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("spherize"),
       QStringLiteral("Spherize"), QStringLiteral("Distort"),
       QStringLiteral("Project image across a sphere."),
       QStringLiteral("spherize fisheye bulge")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("liquify"),
       QStringLiteral("Liquify"), QStringLiteral("Distort"),
       QStringLiteral("Locally push, pull, and swirl image regions."),
       QStringLiteral("liquify warp push pull swirl")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("stroke"),
       QStringLiteral("Stroke"), QStringLiteral("Stylize"),
       QStringLiteral("Draw an outline around the layer alpha."),
       QStringLiteral("stroke outline border alpha")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("inner_shadow"),
       QStringLiteral("Inner Shadow"), QStringLiteral("Stylize"),
       QStringLiteral("Add a shaded inset edge inside the layer alpha."),
       QStringLiteral("inner shadow inset edge")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("bevel"),
       QStringLiteral("Bevel"), QStringLiteral("Stylize"),
       QStringLiteral("Create a beveled edge from the layer alpha."),
       QStringLiteral("bevel emboss edge")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("satin"),
       QStringLiteral("Satin"), QStringLiteral("Stylize"),
       QStringLiteral("Apply a satin-like internal shading effect."),
       QStringLiteral("satin shading stylize")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("rim_light"),
       QStringLiteral("Rim Light"), QStringLiteral("Stylize"),
       QStringLiteral("Highlight the silhouette edge of a layer."),
       QStringLiteral("rim light edge light silhouette")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("radial_blur"),
       QStringLiteral("Radial Blur"), QStringLiteral("Blur"),
       QStringLiteral("Blur outward or around a focal point."),
       QStringLiteral("radial blur zoom spin")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("linear_wipe"),
       QStringLiteral("Linear Wipe"), QStringLiteral("Transition"),
       QStringLiteral("Reveal or hide the layer along a linear boundary."),
       QStringLiteral("linear wipe reveal transition")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("kaleidoscope"),
       QStringLiteral("Kaleidoscope"), QStringLiteral("Stylize"),
       QStringLiteral("Repeat and mirror the image around a center point."),
       QStringLiteral("kaleidoscope mirror repeat")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("dithering"),
       QStringLiteral("Dithering"), QStringLiteral("Stylize"),
       QStringLiteral("Add controlled dither noise for tonal breakup."),
       QStringLiteral("dither noise quantize")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("kuwahara"),
       QStringLiteral("Kuwahara"), QStringLiteral("Stylize"),
       QStringLiteral("Apply edge-preserving painterly smoothing."),
       QStringLiteral("kuwahara painterly smoothing")},
      {EffectPipelineStage::Rasterizer, QStringLiteral("radio_waves"),
       QStringLiteral("Radio Waves"), QStringLiteral("Generate"),
       QStringLiteral("Generate animated expanding wave rings."),
       QStringLiteral("radio waves rings generate")},
      {EffectPipelineStage::Rasterizer,
       QStringLiteral("effect.colorcorrection.grayscale"),
       QStringLiteral("Grayscale"), QStringLiteral("Color"),
       QStringLiteral("Convert the layer to grayscale."),
       QStringLiteral("grayscale desaturate monochrome")},
      {EffectPipelineStage::LayerTransform,
       QStringLiteral("transform_2d"),
       QStringLiteral("Transform 2D"), QStringLiteral("Layer Transform"),
       QStringLiteral("Per-layer transform effect stack control."),
       QStringLiteral("transform position scale rotation layer")},
  };
}

bool effectCatalogEntryMatches(const EffectCatalogEntry &entry,
                               const QString &query) {
  const QString trimmed = query.trimmed();
  if (trimmed.isEmpty()) {
    return true;
  }
  return entry.displayName.contains(trimmed, Qt::CaseInsensitive) ||
         entry.category.contains(trimmed, Qt::CaseInsensitive) ||
         entry.description.contains(trimmed, Qt::CaseInsensitive) ||
         entry.keywords.contains(trimmed, Qt::CaseInsensitive) ||
         entry.effectId.contains(trimmed, Qt::CaseInsensitive);
}


}
